name: Update Version Tags

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get tag info
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=$(echo $TAG | cut -d. -f1)
          MINOR_VERSION=$(echo $TAG | cut -d. -f1,2)
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "major=$MAJOR_VERSION" >> $GITHUB_OUTPUT
          echo "minor=$MINOR_VERSION" >> $GITHUB_OUTPUT
      
      - name: Update major and minor version tags
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -fa ${{ steps.tag.outputs.major }} -m "Update major version tag to ${{ steps.tag.outputs.tag }}"
          
          git tag -fa ${{ steps.tag.outputs.minor }} -m "Update minor version tag to ${{ steps.tag.outputs.tag }}"
          
          git push origin ${{ steps.tag.outputs.major }} --force
          git push origin ${{ steps.tag.outputs.minor }} --force 